name: 'Deploy to michci.ooo'
description: 'Deploy to michci.ooo'
inputs:
  token:
    description: secret token
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: curl -u ${{ github.event.repository.name }}:${{ inputs.token }} -X POST https://michci.ooo/deploy
